from __future__ import annotations

import json
import re
from pathlib import Path
from typing import TYPE_CHECKING

from scripts.feature.compiler import (
    generate_fea_string,
    generate_fea_string_cn_only,
    get_all_calt_text,
    get_cv_cn_desc,
    get_cv_desc,
    get_cv_italic_desc,
    get_freeze_moving_rules,
    get_ss_desc,
    get_total_feat_dict,
)
from scripts.utils.files import write_json
from scripts.utils.logging import TaskName, log_task, logger

if TYPE_CHECKING:
    import argparse


def register_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]):
    parser = subparsers.add_parser("fea", help="Build fea files")
    parser.add_argument(
        "--output", type=str, default="./sources/features", help="Output directory"
    )
    return parser


def replace_section(md_path: str | Path, border: str, content: str) -> None:
    target = Path(md_path)
    md_content = target.read_text(encoding="utf-8")
    if md_content.count(border) != 2:
        raise ValueError(
            f"Expected exactly one section delimited by {border!r} in {md_path}"
        )
    pattern = f"{re.escape(border)}(.*?){re.escape(border)}"
    updated_content, matches = re.subn(
        pattern, f"{border}\n{content}\n{border}", md_content, flags=re.DOTALL
    )
    if matches != 1:
        raise ValueError(f"Ambiguous generated section {border!r} in {md_path}")
    if updated_content == md_content:
        return
    temporary = target.with_name(f".{target.name}.tmp")
    temporary.write_text(updated_content, encoding="utf-8", newline="\n")
    temporary.replace(target)


def update_feature_freeze(file_path: str | Path, features: dict[str, str]) -> None:
    path = Path(file_path)
    config = json.loads(path.read_text(encoding="utf-8"))
    config["feature_freeze"] = dict.fromkeys(features, "ignore")
    write_json(path, config)


def update_schema(file_path: str | Path, features: dict[str, str]) -> None:
    path = Path(file_path)
    schema = json.loads(path.read_text(encoding="utf-8"))
    schema["properties"]["feature_freeze"]["properties"] = {
        tag: {"description": desc, "$ref": "#/definitions/freeze_options"}
        for tag, desc in features.items()
    }
    write_json(path, schema)


def build_fea(output: str) -> None:
    log_task(TaskName.FEA, "Generate feature files: output=%s", output)
    output_dir = Path(output)
    output_dir.mkdir(parents=True, exist_ok=True)
    banner = "Auto generated by `python task.py fea`"
    files = {
        "regular.fea": generate_fea_string(is_italic=False, is_cn=False),
        "italic.fea": generate_fea_string(is_italic=True, is_cn=False),
        "cn.fea": generate_fea_string_cn_only(),
    }
    for filename, content in files.items():
        fea_path = output_dir / filename
        fea_path.write_text(f"# {banner}\n\n{content}", encoding="utf-8", newline="\n")
        logger.info("Saved feature file to %s", fea_path)

    files_cn = {
        "regular_cn.fea": generate_fea_string(is_italic=False, is_cn=True),
        "italic_cn.fea": generate_fea_string(is_italic=True, is_cn=True),
    }
    for filename, content in files_cn.items():
        fea_path = output_dir / filename
        fea_path.write_text(f"# {banner}\n\n{content}", encoding="utf-8", newline="\n")
        logger.info("Saved feature file to %s", fea_path)

    md_path = Path("documentation") / "opentype-features.md"
    sections = {
        "<!-- CALT -->": get_all_calt_text(),
        "<!-- CV -->": get_cv_desc(),
        "<!-- CV-IT -->": get_cv_italic_desc(),
        "<!-- CV-CN -->": get_cv_cn_desc(),
        "<!-- SS -->": get_ss_desc(),
    }
    for border, content in sections.items():
        replace_section(md_path, border, content)
    logger.info("Synchronized feature documentation: path=%s", md_path)

    features = get_total_feat_dict()
    schema_path = Path("sources") / "schema.json"
    update_schema(schema_path, features)
    update_feature_freeze(Path("config.json"), features)
    logger.info("Synchronized feature schema: path=%s", schema_path)
    logger.info("Synchronized feature configuration: path=config.json")

    script_path = Path("scripts") / "in_browser.py"
    in_browser_script = script_path.read_text(encoding="utf-8")
    rules = get_freeze_moving_rules()
    rules.sort()
    rule_arr_text = "[" + ", ".join([f'"{item}"' for item in rules]) + "]"
    patched = re.sub(
        r"MOVING_RULES = .*",
        f"MOVING_RULES = {rule_arr_text}",
        in_browser_script,
    )
    script_path.write_text(patched, encoding="utf-8", newline="\n")
    logger.info("Synchronized browser feature rules: path=%s", script_path)


def run(args: argparse.Namespace) -> None:
    build_fea(args.output)
